/**
============================================
🧠 Prime DICTIONARY MEANING BUILDER v1
============================================

Features:

✅ Reads downloaded words
✅ Creates structured dictionary
✅ Adds basic word information
✅ Removes invalid entries
✅ Prepares for AI learning

============================================
*/


const fs = require("fs");
const path = require("path");





const inputFile =
path.join(
__dirname,
"rawWords.json"
);




const outputFile =
path.join(
__dirname,
"englishWords.json"
);







function build(){



console.log(
"🧠 Building dictionary..."
);





if(
!fs.existsSync(inputFile)
){

console.log(
"❌ rawWords.json not found"
);

return;

}





const raw =
JSON.parse(

fs.readFileSync(
inputFile,
"utf8"
)

);






const words=[];







for(const word of Object.keys(raw)){



// remove bad entries

if(

word.length < 2 ||

word.length > 30 ||

!/^[a-zA-Z]+$/.test(word)

){

continue;

}







words.push({

word:
word.toLowerCase(),


type:
"unknown",


meaning:
"Meaning will be added by knowledge system.",


example:
"Example will be generated by Prime."

});


}









fs.writeFileSync(

outputFile,


JSON.stringify(

words,

null,

2

)

);







console.log(
"🔥 Dictionary file created"
);



console.log(

"📚 Total words:",

words.length

);



}






build();